= Google Chat Notify Resource image:https://ci.spring.io/api/v1/teams/google-chat-notify-resource/pipelines/google-chat-notify-resource/jobs/build/badge["Build Status", link="https://ci.spring.io/teams/google-chat-notify-resource/pipelines/google-chat-notify-resource?groups=Build"]
:google-chat-notify-resource-release-version: ${releaseVersion}
:google-chat-notify-resource-snapshot-version: ${nextVersion}

A https://concourse.ci/[Concourse] resource to send build status notifications to a Google Chat space.



== Overview
This Concourse resource can be used to send notification of build status to a Google Chat space.



== Configuration



=== Resource Configuration
To use the `google-chat-notify-resource` you must declare it in the `resource_types` section of your `pipeline.yml` file:

[source,yml,subs="verbatim,attributes"]
.Resource configuration
----
resource_types:
- name: google-chat-notify-resource
  type: docker-image
  source:
    repository: springio/google-chat-notify-resource
    tag: {google-chat-notify-resource-release-version}
----



=== Source Configuration
* `url`: *Required.* The Google Chat webhook URL

[source,yaml]
.Source configuration
----
resources:
- name: notify
  type: google-chat-notify-resource
  source:
    url: https://chat.googleapis.com/v1/spaces/{{SPACE_ID}}/messages?key={{WEBHOOK_KEY}}&token={{WEBHOOK_TOKEN}}
----


== Behavior

=== `check`: No operation

=== `in`: No operation

=== `out`: Send a message to the webhook

Sends a message containing details of the build to a Google Chat space.



==== Parameters

- `text`: Text of a https://developers.google.com/chat/format-messages#format-texts[formatted text message] to send.
- `card_file`: File that contains a https://developers.google.com/chat/format-messages#card-formatting[formatted card] in JSON format.
- `text_file`: File that contains text that can be sent or included in the `text` or `card_file`.
This allows the message to be generated by a previous task step in the Concourse job.

At least one of these parameters must be provided, and all may be provided:

- If both `text` and `card_file` are provided, both will be used and the text will appear above the card.
- If `text` is provided, then the contents of `text_file` can be included in the message using the environment variable
    `${TEXT_FILE_CONTENT}`.
- If `card_file` is provided, then the contents of `text_file` can be included in any of the JSON fields in the file using the environment variable `${TEXT_FILE_CONTENT}`.
- If only `text_file` is provided, then the contents of the file will be sent as a formatted text message.

Users can be mentioned in the `text` field using the syntax `<users/{userID}>` or `<users/all>`.
Users can not be mentioned in text in a card.


== Example
The following example shows a pipeline with a job that sends a notification to a Google Chat space on completion.

[source,yml,subs="verbatim,attributes"]
.Example pipeline
----
resource_types:
- name: google-chat-notify-resource
  type: docker-image
  source:
    repository: springio/google-chat-notify-resource
    tag: {google-chat-notify-resource-release-version}

resources:
- name: git-repo
  type: git
  source:
    uri: https://git.example.com/my-org/my-project
    branch: main
- name: notify
  type: google-chat-notify-resource
  source:
    url: https://chat.googleapis.com/v1/spaces/{{SPACE_ID}}/messages?key={{WEBHOOK_KEY}}&token={{WEBHOOK_TOKEN}}

jobs:
- name: build
  plan:
  - get: git-repo
    trigger: true
  - task: build
    file: git-repo/samples/simple/tasks/build.yml
    on_failure:
      do:
      - put: notify
        params:
          text: |
            <users/all>
            Failed! https://concourse.example.com/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}
            Result: ${TEXT_FILE_CONTENT}
          text_file: results/message.txt
  - put: notify
    params:
      text: |
        Passed! https://concourse.example.com/teams/${BUILD_TEAM_NAME}/pipelines/${BUILD_PIPELINE_NAME}/jobs/${BUILD_JOB_NAME}/builds/${BUILD_NAME}
        Result: ${TEXT_FILE_CONTENT}
      text_file: results/message.txt
----
