---
platform: linux
image_resource:
  type: registry-image
  source:
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: concourse/oci-build-task
    tag: '0.11.0'
inputs:
- name: git-repo
- name: built-artifact
outputs:
- name: image
caches:
- path: google-chat-notify-resource-image-cache
params:
  DOCKERFILE: git-repo/Dockerfile
  BUILD_ARG_executable: built-artifact/google-chat-notify-resource
  BUILD_ARG_root: git-repo
  DOCKER_HUB_AUTH: ((docker-hub-auth))
run:
  path: /bin/sh
  args:
  - "-c"
  - |
    mkdir -p /root/.docker
    cat > /root/.docker/config.json <<EOF
    { "auths": { "https://index.docker.io/v1/": { "auth": "$DOCKER_HUB_AUTH" }}}
    EOF
    build
