---
platform: linux
image_resource:
  type: registry-image
  source:
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: springio/github-changelog-generator
    tag: '0.0.8'
inputs:
- name: git-repo
- name: built-artifact
outputs:
- name: generated-changelog
params:
  GITHUB_USERNAME: ((github-username))
  GITHUB_TOKEN: ((github-ci-release-token))
run:
  path: git-repo/ci/scripts/generate-changelog.sh
