== Sample Pipeline

To run the sample pipeline using Docker Compose, follow these steps:

=== Install Docker compose
Follow https://docs.docker.com/compose/install/[these instructions] to install Docker Compose if you've not already done so in the past.

=== Start Concourse CI
From this directory, run:

----
$ docker compose up
----

This should start containers for Concourse and a Docker registry.
You should find that Concourse is running at http://127.0.0.1:8080[127.0.0.1:8080] the registry should be running on port 5000.


=== Push the google-chat-notify-resource image
You need to push the `google-chat-notify-resource` image into the container registry.

To build the project locally, first ensure you have the prerequisites for building a Spring Boot application to a native executable as documented in the https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#native-image.developing-your-first-application.native-build-tools[Spring Boot documentation].

Then build and push the image:

----
$ ./mvnw native:compile -Pnative
$ docker build . --tag localhost:5000/google-chat-notify-resource
$ docker push localhost:5000/google-chat-notify-resource
----


=== Deploy the sample pipeline
To deploy the sample pipeline first http://127.0.0.1:8080[download and install fly] then run the following:

----
$ fly --target sample login --concourse-url http://127.0.0.1:8080 -u test -p test
$ fly --target sample sync
----

You should now be able to deploy the pipeline with:

----
$ fly --target sample set-pipeline -p sample -c simple/pipeline.yml -v WEBHOOK_URL=<URL of outgoing webhook>
----

Browse to  http://127.0.0.1:8080/teams/main/pipelines/sample and login with `test`/`test` to see the pipeline.


=== Unpause and trigger the jobs
The newly deployed pipeline will be paused, so you'll either need to unpause it from the web UI or run:

----
$ fly --target sample unpause-pipeline -p sample
----

When the pipeline is active, you can manually trigger the `build` job to see a successful build message sent to the Google Chat space.

----
$ fly --target sample trigger-job -j sample/build
----

You can also manually trigger the `build-fail` job to see a failed build message sent to the Google Chat space.

----
$ fly --target sample trigger-job -j sample/build-fail
----
