== Sample Pipeline

To run the sample pipeline using Docker Compose, follow these steps:

=== Install Docker compose
Follow https://docs.docker.com/compose/install/[these instructions] to install Docker Compose if you've not already done so in the past.

=== Start Concouse CI
From this directory, run:

----
$ docker compose up
----

This should start containers for Concourse and a Docker registry.
You should find that Concourse is running at http://127.0.0.1:8080[127.0.0.1:8080] the registry should be running on port 5000.


=== Push google-chat-notify-resource Image
You need to push the `google-chat-notify-resource` image into the container registry.

To build the project locally, build, and push the image:

----
$ ./gradlew nativeCompile
$ docker build . --tag localhost:5000/google-chat-notify-resource
$ docker push localhost:5000/google-chat-notify-resource
----


=== Deploy the sample pipeline
To deploy the sample pipeline first http://127.0.0.1:8080[download and install fly] then run the following:

----
$ fly --target sample login --concourse-url http://127.0.0.1:8080 -u test -p test
$ fly --target sample sync
----

You should now be able to deploy the pipeline with:

----
$ fly --target sample set-pipeline -p sample -c simple/pipeline.yml -v WEBHOOK_URL=<URL of outgoing webhook>
----

Browse to  http://127.0.0.1:8080/teams/main/pipelines/sample and login with `test`/`test` to see the pipeline.


=== Unpause and trigger the job
The newly deployed pipeline will be paused, so you'll either need to unpause it from the web UI or run:

----
$ fly --target sample unpause-pipeline -p sample
----

When the pipeline is active, you can manually trigger the `build` job.

----
$ fly --target sample trigger-job -j sample/build
----



=== Inspect Artifactory
Once the job has finished you can http://127.0.0.1:8081/artifactory[go back to Artifactory] and login with `admin`/`password`.
Click on the "builds" tab and you should see the build that just ran.
You can also browse the `example-repo-local` repository to see the deployed jar file.

